name: On Pull Actions
on:  
  pull_request:
    branches:
      - main
env:
  REGISTRY: docker.io
  DOCKER_USER_SPACE: kevmeans
  IMAGE_NAME: python-microservice
  PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  HELM_REPO: kevinmeans/kuberentes-manifest
  HELM_PATH: overlays/dev/kustomization.yaml
  
jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.10"]
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint -d C0116,E0401,C0114 $(git ls-files '*.py')
        continue-on-error: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest 
          pytest tests/*test*.py
  build-push:
    name: Build image and push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.DOCKER_USER_SPACE}}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.ref }}-${{ env.PR_COMMIT_SHA }}


