name: CI pipeline

on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  DOCKER_USER_SPACE: kevmeans
  IMAGE_NAME: python-microservice-test
  COMMIT_SHA: ${{ github.sha }}
  HELM_REPO: kevinmeans/kuberentes-manifest
  HELM_PATH: overlays/dev/kustomization.yaml
  
jobs:
  build-push:
    name: Build image and push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.DOCKER_USER_SPACE}}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
  edit-tag:
    runs-on: ubuntu-latest
    name: Change image tag in helm repository
    steps:
    - name: Checkout Helm Repo
      uses: actions/checkout@master
      with: 
        repository: ${{ env.HELM_REPO}}
        token: ${{ secrets.ACTIONS_TOKEN}}
    - name: Change Image Hash
      run: |
          sed -E -i 's/(newTag: )[[:alnum:]]+/\1${{env.COMMIT_SHA}}/' ${{env.HELM_PATH}}
    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config --global user.email "botman@gmail.com"
        git add ${{env.HELM_PATH}}
        git commit -m "Bot Action"
        git push origin main

