name: CI pipeline

on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  DOCKER_USER: kevmeans
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint -d C0116,E0401,C0114 $(git ls-files '*.py')
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          #tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
          tags: kevmeans/python-microservice-test:123























  # push:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-microservice-test
  #         path: /tmp
  #     - 
  #       name: prepare tag info
  #       run: |
  #           TAG=$(echo $GITHUB_SHA | head -c7)
  #           IMAGE="kevmeans/python-microservice-test"
  #           echo ::set-output name=tagged_image::${IMAGE}:${TAG}
  #           echo ::set-output name=tag::${TAG}
  #     -
  #       name: Load image
  #       run: |
  #         docker load --input /tmp/python-microservice-test.tar
  #         docker image ls -a
    

  #         push_to_registry:
  #           name: Push Docker image to Docker Hub
  #           runs-on: ubuntu-latest
  #           steps:
  #             - name: Check out the repo
  #               uses: actions/checkout@v3
              
  #             - name: Log in to Docker Hub
  #               uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
  #               with:
  #                 username: ${{ secrets.DOCKER_USERNAME }}
  #                 password: ${{ secrets.DOCKER_PASSWORD }}
              
  #             - name: Extract metadata (tags, labels) for Docker
  #               id: meta
  #               uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
  #               with:
  #                 images: my-docker-hub-namespace/my-docker-hub-repository
              
  #             - name: Build and push Docker image
  #               uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
  #               with:
  #                 context: .
  #                 file: ./Dockerfile
  #                 push: true
  #                 tags: ${{ steps.meta.outputs.tags }}
  #                 labels: ${{ steps.meta.outputs.labels }}